def get_text(language):
    return {
        'uz':{
            'title': 'Yuz jag’ Jarrohligi — Mutaxassislar jamoasi, xavfsiz va samarali jarrohlik',
            'doctors': 'SHIFOKORLAR',
            'results': 'NATIJALAR',
            'patients': 'BEMORLAR FIKRLARI',
            'consultation': 'KONSULTATSIYA OLISH',
            'address': 'MANZIL',
            'tashkent_address': '📍 TOSHkent shahri, Yashnobod tumani, Olimkent ko‘chasi, 32 uy',
            'andijan_address': "📍 Andijon shahri, Otabekov ko'chasi, 4-B uy",
            'hero_title': 'Yuz sohasi kasalliklarining zamonaviy yechimi',
            'hero_desp':'Tajribali jarrohlar jamoasi bilan yuzingizni tabiiy holatiga qaytaring: estetik ko‘rinish, og‘riqsiz holat, mukammal simmetriya.',
            'acceptance': 'Qabulga yozilish  ',
            'international_experience': 'Xalqaro tajriba',
            'experience_description': "Biz yuz jag’ jarrohligi sohasida 15 yildan ortiq tajribaga ega mutaxassislar jamoasi sifatida, har bir bemor uchun individual va puxta rejalashtirilgan jarrohlik protseduralarini taqdim etamiz.",
            'experience_description2':"15 yildan oshiq tajribaga ega yuz jag' jarroxi, zamonaviy yondashuv va yuzlab bemorlarning sog‘lig‘ini tiklashga hissa qo‘shgan mutaxassis. Dr. Akmal Hakimov yuz jag‘ sohasidagi jarrohlik bo‘yicha O‘zbekistonda yetakchi mutaxassislardan biridir.",
            'stats_successfuly_operations':'Muvaffaqiyatli amalga oshirilgan operatsiyalar',
            'stats_face_bone_operations':'Yuz suyaklari singanda operatsiyalar',
            'stats_orthognathic_operations':'Ortognaik operatsiyalar',
            'stats_oncological_operations':'Yuz sohasi ankologiyasi',
            'stats_ankylosis_arthroplasty':'Ankilozda artroplastika',
            'stats_face_reconstruction_operations':'Yuz sohasi qayta tiklov operatsiyasi',
            'why_us': 'Nima uchun biz?',
            'your_health_and_safety': 'Sizning sog‘lig‘ingiz va xavfsizligingiz — bizning birinchi ustuvorligimiz!',
            'why_us_desp': "Biz yuz jag‘ jarrohligi sohasida 15 yildan ortiq tajribaga ega mutaxassislar jamoasi sifatida, har bir bemor uchun individual va puxta rejalashtirilgan jarrohlik protseduralarini taqdim etamiz. Operatsiyadan oldin barcha jarayonlar aniq va shaffof rejalashtiriladi, shunda siz hech qanday noaniqlik yoki qo‘rquv his qilmasligingizga ishonch hosil qilasiz.",
            'doctor_type': "Professional yuz jag' jarrohi",
            'ortogonblender_description': "3D rejalashtirish platformasi bo‘yicha yetuk mutaxassis, MDHdagi rasmiy vakillardan biri",
            'upgrade_and_international_experience': "Malaka oshirish va xalqaro tajriba:",
            'master_degree_in_jaw_surgery': "Yuz jag’ jarrohligi sohasida magistrlik diplomiga ega",
            'practical_experience_with_ortognatica_roma': "Itali­yadagi “OrgnaticaRoma” ortognatik jarrohlik jamoasi bilan hamkorlikda amaliy tajriba",
            'virtual_training_seminar_in_south_korea': "Janubiy Koreyada “Ortognatik operatsiyalarga virtual tayyorgarlik” seminari",
            'internship_at_artemis_clinic_in_india': "Hindiston, “ARTEMIS” klinikasida “Minimally invasive maxillofacial surgery” bo‘yicha amaliyot",
            'practical_experience':"Yuz jag' jarroxligi sohasida magistrlik diplomiga ega Yuz jarohatlarini zamonaviy davolash va ortognatik operatsiyalar bo'yicha Rossiya Federatsiyasida malaka oshirgan",
            'certificates':"Litsenziya va sertifikatlar",
            'faq_title': 'Savol javoblar',
            'faq1_question': "Savol: Operatsiyadan so'ng yuzda chandiqlar qoladimi?",
            'faq1_answer': "Operatsiyalar asosan og'iz ichi kesmasi bilan amalga oshiriladi va yuzda ko'zga ko'rinarli chandiqlar qolmaydi!",
            'faq2_question': "Savol: Operatsiyadan so'ng necha kundan keyin bemalol ovqatlanish mumkin?",
            'faq2_answer': "Operatsiyadan 3-5 kundan keyin bemalol ovqatlanishingiz mumkin bo'ladi!",
            'faq3_question': "Savol: Operatsiyalar narxi qancha?",
            'faq3_answer': "Operatsiya narxi bemorning holatidan kelib chiqib belgilanadi! Ya'ni operatsiyamizning qanchalik og'ir va murakkab ekanligidan kelib chiqadi.",
            'name': "Ismingiz",
            'phone': "Telefon raqam",
            'consultation_desp': "Sizda yoki tanishlaringizda yuqorida sanab o‘tilgan kasalliklar bilan bog‘liq muammolar bormi? Darhol konsultatsiyaga ro‘yxatdan o‘ting yordam berishga tayyormiz!",
            'footer_title':"2025 Yuz jag' jarrohligi",
            'contacts':"ALOQA",
            'working_hours':"ISH VAQTI",
            'in_andijan':"Andijon shahrida",
            'in_tashkent':"Toshkent shahrida",
            'tashkent_time':"Dushanba–Chorshanba: 09:00 - 18:00",
            'andijan_time':"Payshanba–Shanba: 09:00 - 18:00"

        },
        'ru':{
            'title': 'Лицо челюстной хирургии — Команда специалистов, безопасная и эффективная хирургия',
            'doctors': 'ВРАЧИ',
            'results': 'РЕЗУЛЬТАТЫ',
            'patients': 'МНЕНИЯ ПАЦИЕНТОВ',
            'consultation': 'КОНСУЛЬТАЦИЯ',
            'address': 'АДРЕС',
            'tashkent_address': '📍 Ташкент, Яшнабадский район, улица Олимкент, дом 32',
            'andijan_address': '📍 Андижан, улица Отабекова, дом 4-Б',
            'hero_title': 'Современное решение проблем в области лицевой хирургии',
            'hero_desp':'Восстановите естественное состояние вашего лица с командой опытных хирургов: эстетический вид, безболезненное состояние, идеальная симметрия.',
            'acceptance': 'Записаться на прием',
            'international_experience': 'Международный опыт',
            'experience_description': "Мы, команда специалистов с более чем 15-летним опытом в области челюстно-лицевой хирургии, предлагаем индивидуально и тщательно спланированные хирургические процедуры для каждого пациента.",
            'experience_description2':"Челюстно-лицевой хирург с более чем 15-летним опытом работы, современным подходом и специалистом, внесшим вклад в восстановление здоровья сотен пациентов. Доктор Акмаль Хакимов — один из ведущих специалистов в области челюстно-лицевой хирургии в Узбекистане.",
            'stats_successfuly_operations':'Успешно проведенные операции',
            'stats_face_bone_operations':'Операции при переломах лицевых костей',
            'stats_orthognathic_operations':'Ортогнакие операции',
            'stats_oncological_operations':'Операции по онкологии лицевой области',
            'stats_ankylosis_arthroplasty':'Операции при анкилозах',
            'stats_face_reconstruction_operations':'Операции по реконструкции лица',
            'why_us': 'Почему мы?',
            'your_health_and_safety': 'Ваше здоровье и безопасность — наш главный приоритет!',
            'why_us_desp': "Мы, команда специалистов с более чем 15-летним опытом в области челюстно-лицевой хирургии, предлагаем индивидуально и тщательно спланированные хирургические процедуры для каждого пациента. Перед операцией все процессы планируются четко и прозрачно, чтобы вы могли быть уверены, что не испытываете никаких неясностей или страхов.",
            'doctor_type': "Профессиональный челюстно-лицевой хирург",
            'ortogonblender_description': "Специалист по 3D-планированию, один из официальных представителей в СНГ",
            'upgrade_and_international_experience': "Повышение квалификации и международный опыт:",
            'master_degree_in_jaw_surgery': "Магистерская степень в области челюстно-лицевой хирургии",
            'practical_experience_with_ortognatica_roma': "Практический опыт в сотрудничестве с командой ортогнатической хирургии “OrgnaticaRoma” в Италии",
            'virtual_training_seminar_in_south_korea': "Виртуальный семинар по подготовке к ортогнатическим операциям в Южной Корее",
            'internship_at_artemis_clinic_in_india': "Стажировка в клинике “ARTEMIS” в Индии по минимально инвазивной челюстно-лицевой хирургии",
            'practical_experience':"Имеет степень магистра по челюстно-лицевой хирургии. Проходил повышение квалификации в Российской Федерации по современным методам лечения травм лица и ортогнатической хирургии.",
            'certificates':"Лицензия и сертификаты",
            'faq_title': 'Часто задаваемые вопросы',
            'faq1_question': 'Вопрос: Останутся ли шрамы на лице после операции?',
            'faq1_answer': 'Операции в основном проводятся через внутренний разрез во рту, поэтому на лице не остаются заметные шрамы!',
            'faq2_question': 'Вопрос: Останутся ли шрамы на лице после операции?',
            'faq2_answer': 'Операции в основном проводятся через внутренний разрез во рту, поэтому на лице не остаются заметные шрамы!',
            'faq3_question': 'Вопрос: Какова стоимость операций?',
            'faq3_answer': 'Стоимость операции определяется состоянием пациента! То есть, она зависит от сложности и тяжести нашей операции.',
            'name': "Ваше имя",
            'phone': "Телефон",
            'consultation_desp': "У вас или ваших знакомых есть проблемы с перечисленными выше заболеваниями? Запишитесь на консультацию прямо сейчас, мы готовы помочь!",
            'footer_title':"2025 Челюстно-лицевая хирургия",
            'contacts':"КОНТАКТЫ",
            'working_hours':"РАБОЧИЕ ЧАСЫ",
            'in_andijan':"В Андижане",
            'in_tashkent':"В Ташкенте",
            'tashkent_time':"Понедельник–среда: 09:00 - 18:00",
            'andijan_time':"Четверг–Суббота: 09:00 - 18:00"

        }
    }[language]