# Generated by Django 5.2.5 on 2025-08-11 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_operations_operationsimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='main.category'),
        ),
        migrations.AlterField(
            model_name='operationsimages',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_images', to='main.operations'),
        ),
    ]
