# Generated by Django 5.2.5 on 2025-08-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_operations_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='description',
        ),
    ]
