# Generated by Django 5.2.5 on 2025-08-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_description_ru_category_description_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='operation_image/'),
        ),
    ]
