BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

  XXXXXXX gettext(u'Yuz jag’ Jarrohligi — Mutaxassislar jamoasi, xavfsiz va samarali jarrohlik') XXXXXXXX

  XXXX XXXXXXX XXXX XXXX XXX
  XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXX XXXXXXX XX XXXXXXXX XXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XX XXXXXX XXXXX XXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX

  XXXX XXXX XXXXX X XXXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXX XXXXXXX XX XXXXXXXX XXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XX XXXXXX XXXXX XXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXX XXXXXXX XX XXXXXXXX XXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XX XXXXXX XXXXX XXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXX XXX XXXX XXXX XXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX XXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX


XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX


  XXXX XXXXXX XXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX
XXXXXX


    XXXX XXXXXXX XXXX XXX


XXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      
      XXXX XXXX XXX
          XX
            XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
          X
            XXXX
              XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX
              XXXXXXXX XXXX XXXXXXXXXX XXXXXXXXX
              XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX
              XXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXX
              XXXXXXXXXXX
              XXXXXXXXXXX
            XX
            XXXX
              XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
              XXXXXXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXX
              XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX
              XXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXX
              XXXXXXXXXXX
              XXXXXXXXXXX
            XX
          XXXX

      XXXX XXXXXXX XXX XXX
      XXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'SHIFOKORLAR') XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'NATIJALAR') XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'BEMORLAR FIKRLARI') XXXX
        XXXXX
      XXXXX

      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX

        XXXX XXXXXXXX XXXXXXXX XXX
      BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
        XX 
          XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX 
          XXXXXXXX 
          XXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXX
        X
          BB BBBBBBBBBBBBB BB BBBB
             XXX
          BBBB
             XXX
          BBBBB
          
        XXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXX
            XX 
              XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXBBBBBX 
              XXXXXXXXXXX 
              XXXXXXXXXXXXXXX
            X
              XXX
            XXXX
          XXXXX
          XXXX
            XX 
              XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXBBBBBX 
              XXXXXXXXXXX 
              XXXXXXXXXXXXXXX
            X
              XXX
            XXXX
          XXXXX
        XXXXX
      XXXXXX

        XXXX XXXXXXXXXXXX XXXXXX XXX
        XX 
          XXXXXXXX 
          XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXX
        X
           gettext(u'KONSULTATSIYA OLISH')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
        XXXX

        XXXX XXXXXX XXXXXXXXX XXX
        XXXXXXX 
          XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX 
          XXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX
        X
          XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXX

      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

XXXX XXXXXXXXX XXXXXX XXXX XXX
XXXX 
  XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX 
  XXXXXXXXXXXXX 
  XXXXXXXXXXXXXXX 
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
X
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXX
            XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX
            XXXXXXXX XXXX XXXXXXXXXX XXXXXXXXX
          XX
    XXXXX
    XXXXXXX 
      XXXXXXXXXXXXX 
      XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX 
      XXXXXXXXXXXXXXXXXXXXXXXXXXX 
      XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'SHIFOKORLAR') XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'NATIJALAR') XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'BEMORLAR FIKRLARI') XXXX
        XXXXX
      XXXXX
    XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXX
        XX 
          XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX 
          XXXXXXXX 
          XXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXX 
          XXXXXXXXXXXXXXXXXXXX
        X
          BB BBBBBBBBBBBBB BB BBBB
            XXX
          BBBB
            XXX
          BBBBB
        XXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXX
            XX 
              XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXBBBBBX 
              XXXXXXXXXXX 
              XXXXXXXXXXXXXXX
            X
              XXX
            XXXX
          XXXXX
          XXXX
            XX 
              XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXBBBBBX 
              XXXXXXXXXXX 
              XXXXXXXXXXXXXXX
            X
              XXX
            XXXX
          XXXXX
        XXXXX
      XXXXXX


    XXXXXXXX XXXXXXXXXXXX XXXXXX
      XX XXXXXXXXXXXXXXXXXX XXXXXX gettext(u'MANZIL') XXXX
      XX XXXXXXXXXXXXX gettext(u'📍 Toshkent shahri, Yashnobod tumani, Olimkent ko‘chasi, 32 uy') XXXX
      XX XXXXXXXXXXXXX gettext(u"📍 Andijon shahri, Otabekov ko'chasi, 4-B uy") XXXX
      XX XXXXXXXXXXXXX gettext(u'☎️ +998 90 529 53 34') XXXX
    XXXXXXXXXX

    XXXX XXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

  XXXXXX
XXXXXX

  XXXX XXXXX XXXX XXX


    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXXXXXXX XXXXXXX
    BB BBBBBBBB
      BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
          
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      BBBBBB
    BBBBB
  XXXXXX
  XXXXXX


  XXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXX

  XXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXX XXX XXXXXXXX XXXXX XX XXXXXX XXXXXXXXX XXX
  XXXX 
    XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX  
    XXXXXXXXXXXXX XXXXXXX XXXXXX 
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX 
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXX  X
    XXXXXXXXXXXXXXXX 
  XX

  XXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX




  XXXX XXXX XXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    

    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Yuz sohasi kasalliklarining zamonaviy yechimi') XXXXX
    XX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX gettext(u'Tajribali jarrohlar jamoasi bilan yuzingizni tabiiy holatiga qaytaring: estetik ko‘rinish, og‘riqsiz holat, mukammal simmetriya.') XXXX
    XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'KONSULTATSIYA OLISH')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX gettext(u'Xalqaro tajriba') XXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
            XX XXXXX XXXX XXX XXXX XXXXXXXXXX XXXXXXXX XX XXXXXX XXXXX XXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX
            XXX XXX XXXXX XXXXX XXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XX
          XXXX
          XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'QABULGA YOZILISH')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX X XXXX
          XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX
          XXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Muvaffaqiyatli amalga oshirilgan operatsiyalar') XXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Yuz suyaklari singanda operatsiyalar') XXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Ortognaik operatsiyalar') XXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Yuz sohasi ankologiyasi') XXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Ankilozda artroplastika') XXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Yuz sohasi qayta tiklov operatsiyasi') XXXX
        XXXXXX
      XXXXXX

    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XX
      XXXXXX

      XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Nima uchun biz ?') XXXXX
        XX XXXXXXXXXXXXXXXXXXXX gettext(u'Sizning sog‘lig‘ingiz va xavfsizligingiz — bizning birinchi ustuvorligimiz!') XXXX
        XX XXXXXXXXXXXXXXXXXXX
          XX XXXXX XXXX XXX XXXX XXXXXXXXXX XXXXXXXX XX XXXXXX XXXXX XXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX
          XXX XXX XXXXX XXXXX XXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXX
          XXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXX XXXX XX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXX XXXX XXXXXX
          XXXXXXXXX XXXX XXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXX XX
        XXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XX
      XXXXXX

    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXX XX XXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXX 
             XXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXX

      XXXX XXXXXXXX XX XXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXX XXXXXXX XXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX gettext(u"Professional yuz jag' jarrohi") XXXX
            XXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              gettext(u'15 yildan ortiq tajribaga ega yuz jag‘ jarrohi. Yuz suyaklari siniq\xadlarini davolash, yuz va jag‘ sohasidagi o‘smalarni olib tashlash, hamda ortognatik jarrohlik bo‘yicha mutaxassis.') 
            XXXX
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'3D rejalashtirish platformasi bo‘yicha yetuk mutaxassis, MDHdagi rasmiy vakillardan biri') 
            XXXX
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXX gettext(u'Malaka oshirish va xalqaro tajriba:') XXXXXXXXXXXXX
               gettext(u'Yuz jag’ jarrohligi sohasida magistrlik diplomiga ega') XXXX
               gettext(u'Itali\xadyadagi “OrgnaticaRoma” ortognatik jarrohlik jamoasi bilan hamkorlikda amaliy tajriba') XXXX
               gettext(u'Janubiy Koreyada “Ortognatik operatsiyalarga virtual tayyorgarlik” seminari') XXXX
               gettext(u'Hindiston, “ARTEMIS” klinikasida “Minimally invasive maxillofacial surgery” bo‘yicha amaliyot') 
            XXXX
          XXXXXX
          XXXX XXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXX XX XXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXX 
             XXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXX

      XXXX XXXXXXXX XX XXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXX XXXXXXX XXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX gettext(u"Professional yuz jag' jarrohi") XXXX
            XXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              gettext(u"15 yildan oshiq tajribaga ega yuz jag' jarroxi, zamonaviy yondashuv va yuzlab bemorlarning sog‘lig‘ini tiklashga hissa qo‘shgan mutaxassis. Dr. Akmal Hakimov yuz jag‘ sohasidagi jarrohlik bo‘yicha O‘zbekistonda yetakchi mutaxassislardan biridir.") 
            XXXX
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXX gettext(u'Malaka oshirish va xalqaro tajriba:') XXXXXXXXXXXXX
               gettext(u"Yuz jag' jarroxligi sohasida magistrlik diplomiga ega") XXXX
               gettext(u'Yuz jarohatlarini zamonaviy davolash va ortognatik operatsiyalar') XXXX
               gettext(u"bo'yicha Rossiya Federatsiyasida malaka oshirgan") 
            XXXX
          XXXXXX
          XXXX XXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX

    XXXXXX
  XXXXXX
XXXXXXXXXX


XXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Litsenziya va Sertifikatlar') XXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XX
        XXXXXX
        XXXX XXXXXX XXXXXXXXXXXXX XXXXX XXXXXX XXX XXXXX XXXXXXXXXX XXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX


 XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Amalga oshiriladigan operatsiyalar') XXXXX
    XXXX XXXXXXXXXX XXXXX
      XXXX XXXX X XXX
      XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXX
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XX
          XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXX XXXXX XX XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX

      XXXX XXXX X XXX
      XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXX
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XX
          XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXX XXXX XXXXXXXXX XXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX

      XXXX XXXX X XXX
      XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXX
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXX XX
          XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XX XXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX

      XXXX XXXX X XXX
      XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXX
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XX
          XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXX XXXX XXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XX XXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Amalga oshirilgan operatsiyalar') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXX XXXXXXXXX XXXX XXXXX XXX
         BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        BBBBBB
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

      XXXX XXXX XXXXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX gettext(u'Xalqaro tajriba') XXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
            XX XXXXX XXXX XXX XXXX XXXXXXXXXX XXXXXXXX XX XXXXXX XXXXX XXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX
            XXX XXX XXXXX XXXXX XXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XX
          XXXX
          XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
             gettext(u'QABULGA YOZILISH')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
          XXXX
        XXXXXX
      XXXXXX

      XXXX XXXX XXXXXX XXXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
          XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
          XXXXXXXXX
        XXXXXX
      XXXXXX

    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXX XXX XXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Savol javoblar') XXXXX

      XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX gettext(u"Savol: Operatsiyadan so'ng yuzda chandiqlar qoladimi?") XXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u"Operatsiyalar asosan og'iz ichi kesmasi bilan amalga oshiriladi va yuzda ko'zga ko'rinarli chandiqlar qolmaydi!") 
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX gettext(u'Savol: Operatsiyadan nechi kundan keyin bemalol ovqatlanish mumkin?') XXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u"Operatsiyadan 3-5 kundan keyin bemalol ovqatlanishingiz mumkin bo'ladi!") 
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX gettext(u'Savol: Operatsiyalar narxi qancha?') XXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u"Operatsiya narxi bemorning holatidan kelib chiqib belgilanadi! Ya'ni operatsiyamizning qanchalik og'ir va murakkab ekanligidan kelib chiqadi!") 
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX


XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX

      XXXX XXX XXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
          XXXXXXX 
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXX XXXXX XXXXXXXXX 
            XXXXXXXXXXXXXXXXXX XXXXXXX 
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
          XXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXX XXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXX XXXXXX gettext(u'Qabulga yozilish') XXXXX
          XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX X
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Ismingiz') XXXXXXXX
              XXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX X XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
            XXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Telefon raqam') XXXXXXXX
              XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX X XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX
               gettext(u'JOY BAND QILISH') 
              XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
          XXXXXXX
        XXXXXX
      XXXXXX

    XXXXXX
  XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXX XXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXXXXXX XX
        XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
           gettext(u'QABULGA YOZILISH')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
        XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX

  XXXXXXX

  
  XXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXX XX
            XXXX
                XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
                XXXXXXXXXXXXXXXXX
                XXXXXXXXXXX
                XXXXXX
              XX
            XXXXX
          XXXX XXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
          XXXXXX
          XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX  gettext(u"2025 Yuz jag' jarrohligi") XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'CONTACTS') XXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXX
           gettext(u'📍 Toshkent: Yashnobod tumani, Olimkent ko‘chasi, 32 uy') 
          XXXX
          XX XXXXXXXXXXXXXXXXX XXXXXX
             gettext(u'📍 Andijon: Otabekov ko‘chasi, 4-B uy') 
          XXXX
          XX XXXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXX XXXX XX XXX XX XX
          XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'ISH VAQTI') XXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Toshkent shahrida:') XXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Dushanba–Chorshanba: 09:00 - 18:00') XXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Andijon shahrida:') XXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Payshanba–Shanba: 09:00 - 18:00') XXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXX









  XXXX XXXXX XXX
  XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
        
        XXXX XXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Qabulga yozilish') XXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
               gettext(u'JOY BAND QILISH')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXX
          XXXXXXX
        XXXXXX

      XXXXXX
    XXXXXX
  XXXXXX

  
  XXXXXXX
    XXXXXXXXXXXXXX X
  XXXXXX XXXXXXXX
  XXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXXXX XXX XXXXX XXXXXXXX
  XXXXXXXX XXXX XXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXX XXXX XX
X

XXXXXXXXXXXX X
  XXXXXX XXXXXXXX
  XXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXXXX XXX XXXXX XXXXXXXX
  XXXXXXXX XXXX XXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXX XXXX XX
X

  XXXXXXXX
  
  
      XXXXXXXX
        XX X XXXXXXXXXXXXXXXXXXXXXXXXXXX X X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XX
        X
    XXXXXXXXX
XXXXXXX

XXXX XXXXXXXXX X XX XXXXX XXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


XXXX XXXXX XX XX XXX

XXXX XXX XX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

XXXX XXXXXX XX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
  XXXXXXX